version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: scipy
    versions:
    - 1.6.0
    - 1.6.1
    - 1.6.2
  - dependency-name: torch
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: torchvision
    versions:
    - 0.8.2
    - 0.9.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
