dist: xenial # for Python versions >= 3.7
language: python

# Python versions
python:
  - "3.5"
  - "3.6"
  - "3.7"

# git settings
git:
  depth: 10

# install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov mock

# run tests
script:
  - export PYTHONPATH=$PYTHONPATH:./
  - pytest --cov-config=.coveragerc --cov=autosynch tests/

# only test phase2
branches:
  only:
    - phase2
